# Generated by Django 4.2.5 on 2023-09-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('date_of_joining', models.DateField(blank=True)),
                ('date_of_birth', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('1', 'Birthday'), ('2', 'WorkAnniversary')], default='1', max_length=255)),
                ('template', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(default='[]', null=True)),
                ('employee_array', models.TextField(default='[]', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('1', 'Birthday'), ('2', 'WorkAnniversary')], max_length=255)),
                ('mail_time', models.DateTimeField(auto_now_add=True)),
                ('employee_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emailApp.employee')),
                ('event_log_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emailApp.eventlog')),
            ],
        ),
    ]
