# Generated by Django 4.2.5 on 2023-10-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailApp', '0002_eventlog_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
